services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wshop_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wshop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./importSql.sql:/docker-entrypoint-initdb.d/importSql.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wshop_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
