/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 8.0.17 : Database - wshop_test
*********************************************************************
*/

CREATE DATABASE IF NOT EXISTS `wshop_test` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `wshop_test`;

/*Table structure for table `product` */

DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(30) NOT NULL DEFAULT '',
  `name` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) DEFAULT NULL,
  `price` FLOAT UNSIGNED NOT NULL,
  `discount_price` FLOAT UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `updated_at` DATETIME DEFAULT NULL COMMENT 'triggered on ADD/MODIF',
  PRIMARY KEY (`id`),
  UNIQUE KEY (`reference`),
  KEY (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `product` */

INSERT INTO `product`
(`id`, `reference`, `name`, `title`, `price`, `discount_price`, `description`, `updated_at`)
values 
(1,'00W003711','Talc Antiseptique Tradicional','Talc Antiseptique Tradicional',8,0,'&sect;Description&sect;Avec sa formule efficace depuis 1903, le Talc antiseptique Tradicional allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes.<br />\r\nIl combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie.&nbsp;&sect;Conseils d&#39;utilisation&sect;Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches.&sect;Composition&sect;talc, starch, sulfur, zinc oxide, boric acid, alicylic acid',NULL),
(2,'00W003712','Talc Antiseptique Fresh','Talc Antiseptique Fresh',8,0,'&sect;Description&sect; Avec sa formule efficace depuis 1903, le Talc antiseptique Fresh allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes. Il combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches. &sect;Composition&sect; talc, starch, sulfur, zinc oxide, boric acid, parfum, salicylic acid.',NULL),
(3,'00W003713','Talc Antiseptique Sport','Talc Antiseptique Sport',8,0,'&sect;Description&sect; Avec sa formule efficace depuis 1903, le Talc antiseptique Sport allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes. Il combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches. &sect;Composition&sect; talc, starch, sulfur, zinc oxide, boric acid, parfum, salicylic acid.',NULL),
(5,'00W003715','Savon Antiseptique Fresh','Savon Antiseptique Fresh',5,0,'&sect;Description&sect; Le savon en pain Antiseptique Fresh offre une protection efficace quotidienne contre les bact&eacute;ries. La pr&eacute;sence d&acute;Oxyde de Zinc dans sa formule permet de r&eacute;guler la production de S&eacute;bum, sans pour autant dess&eacute;cher la peau. Base 100% v&eacute;g&eacute;tale. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. &sect;Composition&sect; elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, benzyl salicylate, citronellol, eugenol,hexyl cinnamal, hydroxyisohexyl 3- cyclohexene carboxaldehyde, isoeugenol, linalool, limonene,butylphenyl methylpropional, alpha- isomethyl ionone. elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, benzyl salicylate, citronellol, eugenol,hexyl cinnamal, hydroxyisohexyl 3- cyclohexene carboxaldehyde, isoeugenol, linalool, limonene,butylphenyl methylpropional, alpha- isomethyl ionone.',NULL),
(6,'00W003716','Savon Antiseptique Sport','Savon Antiseptique Sport',5,0,'&sect;Description&sect; Le savon en pain Antiseptique Sport offre une protection efficace quotidienne contre les bact&eacute;ries. La pr&eacute;sence d&acute;Oxyde de Zinc dans sa formule permet de r&eacute;guler la production de S&eacute;bum, sans pour autant dess&eacute;cher la peau. Base 100% v&eacute;g&eacute;tale. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. &sect;Composition&sect; elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, hexyl cinnamal. elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, hexyl cinnamal.',NULL),
(7,'00W003717','Gel Fraîcheur Anti-Fatigue Sport','Gel Fraîcheur Anti-Fatigue Sport',19,0,'&sect;Description&sect; Le Gel Rafra&icirc;chissant Anti-Fatigue Sport soulage les tensions caus&eacute;es par l&acute;activit&eacute; physique. Il d&eacute;lasse, rafraichi et minimise la sensation de fatigue musculaire. Formule enrichie avec des extraits d&acute;&quot;herba baaleira&quot; et d&acute;huile de menthe. Formule &agrave; absorption rapide avec une texture s&egrave;che et soyeuse. &sect;Conseils d&#39;utilisation&sect; Appliquer de pr&eacute;f&eacute;rence sur peau propre et s&egrave;che. Id&eacute;al apr&egrave;s le sport et/ou avant d&acute;aller se coucher. Peut &ecirc;tre utilis&eacute; quotidiennement. &sect;Composition&sect; aqua (water), glycerin, dimethicone, mentha arvensis leaf oil, propylene glycol, sodium polyacrylate, dimethicone crosspolymer, sorbitan caprylate, cordia verbenacea, cyclopentasiloxane, trideceth-6, PEG/ PPG-18/18 dimethicone, propanediol, benzoic acid, citral, eugenol, limonene, linalool, citronellol.',NULL),
(8,'00W003718','Déodorant Bille Fresh','Déodorant Bille Fresh',8,0,'&sect;Description&sect; Le d&eacute;odorant Roll-On Fresh est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect; aqua (water), aluminum chlorohydrate, steareth-2, dicaprylyl ether, ceteareth-20, cyclomethicone, urea, dimethicone, disodium edta, allantoin, triclosan, methylparaben, propylparaben, bht.',NULL),
(9,'00W003719','Déodorant Bille Sport','Déodorant Bille Sport',8,0,'&sect;Description&sect;Le d&eacute;odorant Roll-On Sport est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect;Aqua (Water), Aluminum Chlorohydrate , Steareth-2, Dicaprylyl Ether , Ceteareth-20,&nbsp; Cyclomethicone , Urea,&nbsp; Dimethicone,&nbsp; Methylparaben,&nbsp; Disodium Edta, Allantoin,&nbsp; Parfum (Fragrance),&nbsp; Triclosan, Propylparaben,&nbsp; Bht, Geraniol, Hexyl Cinnamal.',NULL),
(10,'00W003720','Déodorant Bille Tradicional','Déodorant Bille Tradicional',8,0,'&sect;Description&sect; Le d&eacute;odorant Roll-On Tradicional est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect; aqua (water), aluminum chlorohydrate , steareth-2, dicaprylyl ether , ceteareth-20, cyclomethicone , urea, dimethicone, methylparaben, disodium edta, allantoin, parfum (fragrance), triclosan, propylparaben, bht, geraniol, hexyl cinnamal.',NULL),
(11,'00W003721','Coffret Sport','Coffret Sport',77,0,'&sect;Description&sect; Coffret. &sect;Composition&sect; aqua (water), aluminum chlorohydrate , steareth-2, dicaprylyl ether , ceteareth-20, cyclomethicone , urea, dimethicone, methylparaben, disodium edta, allantoin, parfum (fragrance), triclosan, propylparaben, bht, geraniol, hexyl cinnamal.',NULL),
(16,'00W003722','Gommage poudre pour le visage','Gommage poudre pour le visage',27,0,'&sect;Description&sect; Recommand&eacute; particuli&egrave;rement pour les peaux grasses. Poudre exfoliante qui stimule le renouvellement cellulaire. Avec son effet micro-peeling elle agit en douceur, d&eacute;sobstruant les pores et offrant un nettoyage profond de la peau. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer sur visage humide une &agrave; deux fois par semaine avec des mouvements circulaires. Doser la quantit&eacute; de produit en fonction de l&acute;exfoliation souhait&eacute;e. Bien rincer. Non-indiqu&eacute; pour les peaux sensibles. &sect;Composition&sect; zea mays starch, polyethylene, sodium lauroyl glutamate, talc, mannitol, aqua (water), parfum (fragrance), silica, magnesium carbonate, triclosan, BHT, LIMONENE, LINALOOL.',NULL),
(17,'00W003723','Mousse Lavante Purifiante Visage','Mousse Lavante Purifiante Visage',29,0,'&sect;Description&sect; Nettoie, embellit et hydrate la peau. La Mousse Nettoyante R&eacute;g&eacute;n&eacute;ratrice &eacute;limine les cellules mortes sans endommager ou dess&eacute;cher le visage. Sa formule rafra&icirc;chit, maintient l&acute;hydratation et laisse une sensation extra douce sur la peau. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer sur visage humide par effleurage. Laisser agir 30 secondes, masser d&eacute;licatement en effectuant des mouvements circulaires, et bien rincer. &sect;Composition&sect; aqua, PEG-14M, PPG-5 ceteareth-20, TEA-cocoyl glutamate, polyquaternium 39, phenoxyethanol, caprylyl glycol, Lavandula hybrida oil, glycerin, sodium PCA, sodium lactate, propylene glycol, arginine, aspartic acid, PCA, glycine, alanine, serine, valine, proline, threonine, isoleucine, histidine, phenylalanine, bacillus ferment, limonene.',NULL),
(18,'00W003724','Hydratant corporel de Lactate d’Ammonium','Hydratant corporel de Lactate d’Ammonium',30,0,'&sect;Description&sect; &Eacute;mulsion hautement hydratante. Formul&eacute;e avec du lactate d&#39;ammonium, de l&#39;ur&eacute;e et de l&#39;huile de p&eacute;pins de raisin, elle est sp&eacute;cialement d&eacute;velopp&eacute;e pour les peaux pr&eacute;sentant des rugosit&eacute;s car elle agit en profondeur. Absorbtion rapide. pH neutre et sans colorant. Parfum aux vertus relaxantes. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer une fine couche sur la peau, deux fois par jour, en massant d&eacute;licatement. Ce produit ne doit pas &ecirc;tre utilis&eacute; par les femmes enceintes. &sect;Composition&sect; aqua (water), ammonium lactate, cetearyl alcohol, Vitis vinifera seed oil, glyceryl stearate SE, dimethicone, paraffinum liquidum, urea, triethanolamine, ceteareth-20, Lavandula hybrida oil, sorbitan caprylate, propanediol, benzoic acid, BHT, GERANIOL, LIMONENE, LINALOOL.',NULL),
(19,'00W003725','Savon antiacné','Savon antiacné',5,0,'&sect;Description&sect; Savon &agrave; base v&eacute;g&eacute;tale, enrichi en acide Salicylique (2%) et souffre (10%), indiqu&eacute; pour un usage quotidien pour les peaux grasses et acn&eacute;ique. Avec ses propri&eacute;t&eacute;s k&eacute;ratolytiques et s&eacute;bor&eacute;gulatrices, il nettoie en profondeur et contr&ocirc;le la production de sebum. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. Pour une meilleure efficacit&eacute; antiacn&eacute;, compl&eacute;ter le rituel en appliquant le Fluide hydratant Matifiant Visage. &sect;Composition&sect; Enxofre / sulfur (10%), &Aacute;cido Salic&iacute;lico / salicylic acid (2%), elaeis guineensis kernel oil and stearic acid, zea mays starch , calcium carbonate, talc, BHT, disodium distyrylbiphenyl disulfonate and CI 74160, etidronic acid. Teor de vol&aacute;teis: 18,94%',NULL),
(20,'00W003726','Savon liquide Antiacné à base de Soufre','Savon liquide Antiacné à base de Soufre',15,0,'&sect;Description&sect;Le savon liquide &agrave; base de soufre est indiqu&eacute; pour un usage quotidien et pour tout type de peau. Avec ses propri&eacute;t&eacute;s antiacn&eacute;, il nettoie en profondeur et agit comme pr&eacute;ventif. Pratique &agrave; transporter et &agrave; appliquer. Formule sans huile, au parfum d&acute;Eucalyptus. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer matin et soir sur visage humide et masser d&eacute;licatement jusqu&acute;&agrave; formation d&acute;une mousse abondante. Bien rincer. &sect;Composition&sect;Aqua (Water), Sodium Laureth Sulfate, Cocamide Dea,&nbsp; Decyl Glucoside,&nbsp; Cocamidopropyl Betaine,&nbsp;&nbsp; Glycerin,&nbsp; Parfum (Fragrance), Peg-30 Castor Oil ,Tea Cocoyl Glutamate,&nbsp; Phenoxyethanol, Sodium Chloride, Polyglycreyl-3 Caprylate, Caprylyl Glycol,&nbsp; Peg-150 Distearate,&nbsp; Citric Acid,&nbsp; Buteth-3, Sulfur, Alcohol, Sodium Benzotriazolyl Butylphenol Sulfonate, Tris Tetramethylhydroxypiperidinol Citrate, Tributyl Citrate,&nbsp;&nbsp; Citronellol, Coumarin, Geraniol, Limonene.',NULL);

/*Table structure for table `produit_lang` */

DROP TABLE IF EXISTS `product_lang`;

CREATE TABLE `product_lang` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) DEFAULT NULL,
  `title` VARCHAR(100) DEFAULT NULL,
  `description` TEXT,
  `product_id` INT(11) DEFAULT NULL,
  `lang_id` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY (`product_id`),
  KEY (`lang_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `produit_lang` */

INSERT INTO `product_lang`
(`id`, `name`, `title`, `description`, `product_id`, `lang_id`)
values 
(1,'Talc Antiseptique Tradicional','Talc Antiseptique Tradicional','&sect;Description&sect;Avec sa formule efficace depuis 1903, le Talc antiseptique Tradicional allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes.<br />\r\nIl combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie.&nbsp;&sect;Conseils d&#39;utilisation&sect;Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches.&sect;Composition&sect;talc, starch, sulfur, zinc oxide, boric acid, alicylic acid',1,1),
(2,'Talc Antiseptique Fresh','Talc Antiseptique Fresh','&sect;Description&sect; Avec sa formule efficace depuis 1903, le Talc antiseptique Fresh allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes. Il combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches. &sect;Composition&sect; talc, starch, sulfur, zinc oxide, boric acid, parfum, salicylic acid.',2,1),
(3,'Talc Antiseptique Sport','Talc Antiseptique Sport','&sect;Description&sect; Avec sa formule efficace depuis 1903, le Talc antiseptique Sport allie des actions antiseptiques, antibact&eacute;riennes, fongicides, cicatrisantes et d&eacute;odorantes. Il combat les odeurs de transpiration des aisselles et des pieds, mais aussi l&acute;&eacute;ryth&egrave;me fessier et la miliaria. Il pr&eacute;vient les &eacute;ruptions cutan&eacute;es et les engelures. Cliniquement test&eacute;. Emballage &eacute;conomique. Ne contient pas de chlorhydroxyde d&#39;aluminium minimisant le risque d&acute;allergie. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones d&eacute;sir&eacute;es, propres et s&egrave;ches. &sect;Composition&sect; talc, starch, sulfur, zinc oxide, boric acid, parfum, salicylic acid.',3,1),
(4,'Savon Antiseptique Tradicional','Savon Antiseptique Tradicional','&sect;Description&sect; Le savon en pain Antiseptique Tradicional offre une protection efficace quotidienne contre les bact&eacute;ries. La pr&eacute;sence du souffre dans sa formule permet de contr&ocirc;ler l&#39;acn&eacute; et les pellicules. Base 100% v&eacute;g&eacute;tale. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. &sect;Composition&sect; elaeis guineensis oil and stearic acid and elaeis guineensis kernel oil, disodium distyryl biphenyl disulfonate + c.i 74160, sulfur, zinc oxide, triclosan, parfum, ferula galbaniflua (galbanum) resin oil, starch, citronellol, coumarin, eugenol, geraniol, limonene. elaeis guineensis oil and stearic acid and elaeis guineensis kernel oil, disodium distyryl biphenyl disulfonate + c.i 74160, sulfur, zinc oxide, triclosan, parfum, ferula galbaniflua (galbanum) resin oil, starch, citronellol, coumarin, eugenol, geraniol, limonene.',4,1),
(5,'Savon Antiseptique  Fresh','Savon Antiseptique  Fresh','&sect;Description&sect; Le savon en pain Antiseptique Fresh offre une protection efficace quotidienne contre les bact&eacute;ries. La pr&eacute;sence d&acute;Oxyde de Zinc dans sa formule permet de r&eacute;guler la production de S&eacute;bum, sans pour autant dess&eacute;cher la peau. Base 100% v&eacute;g&eacute;tale. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. &sect;Composition&sect; elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, benzyl salicylate, citronellol, eugenol,hexyl cinnamal, hydroxyisohexyl 3- cyclohexene carboxaldehyde, isoeugenol, linalool, limonene,butylphenyl methylpropional, alpha- isomethyl ionone. elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, benzyl salicylate, citronellol, eugenol,hexyl cinnamal, hydroxyisohexyl 3- cyclohexene carboxaldehyde, isoeugenol, linalool, limonene,butylphenyl methylpropional, alpha- isomethyl ionone.',5,1),
(6,'Savon Antiseptique  Sport','Savon Antiseptique  Sport','&sect;Description&sect; Le savon en pain Antiseptique Sport offre une protection efficace quotidienne contre les bact&eacute;ries. La pr&eacute;sence d&acute;Oxyde de Zinc dans sa formule permet de r&eacute;guler la production de S&eacute;bum, sans pour autant dess&eacute;cher la peau. Base 100% v&eacute;g&eacute;tale. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. &sect;Composition&sect; elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, hexyl cinnamal. elaeis guineensis oil, aqua, tristearin, elaeis guineensis kernel oil, zea mays starch, sodium hydroxide, parfum, lanolin, titanium dioxide, triclosan, tetrasodium edta, etidronic acid, disodium distyrylbiphenyl disulfonate, cellulose gum, hexyl cinnamal.',6,1),
(7,'Gel Fraîcheur Anti-Fatigue Sport','Gel Fraîcheur Anti-Fatigue Sport','&sect;Description&sect; Le Gel Rafra&icirc;chissant Anti-Fatigue Sport soulage les tensions caus&eacute;es par l&acute;activit&eacute; physique. Il d&eacute;lasse, rafraichi et minimise la sensation de fatigue musculaire. Formule enrichie avec des extraits d&acute;&quot;herba baaleira&quot; et d&acute;huile de menthe. Formule &agrave; absorption rapide avec une texture s&egrave;che et soyeuse. &sect;Conseils d&#39;utilisation&sect; Appliquer de pr&eacute;f&eacute;rence sur peau propre et s&egrave;che. Id&eacute;al apr&egrave;s le sport et/ou avant d&acute;aller se coucher. Peut &ecirc;tre utilis&eacute; quotidiennement. &sect;Composition&sect; aqua (water), glycerin, dimethicone, mentha arvensis leaf oil, propylene glycol, sodium polyacrylate, dimethicone crosspolymer, sorbitan caprylate, cordia verbenacea, cyclopentasiloxane, trideceth-6, PEG/ PPG-18/18 dimethicone, propanediol, benzoic acid, citral, eugenol, limonene, linalool, citronellol.',7,1),
(8,'Déodorant Bille Fresh','Déodorant Bille Fresh','&sect;Description&sect; Le d&eacute;odorant Roll-On Fresh est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect; aqua (water), aluminum chlorohydrate, steareth-2, dicaprylyl ether, ceteareth-20, cyclomethicone, urea, dimethicone, disodium edta, allantoin, triclosan, methylparaben, propylparaben, bht.',8,1),
(9,'Déodorant Bille Sport','Déodorant Bille Sport','&sect;Description&sect; Le d&eacute;odorant Roll-On Sport est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect; aqua (water), aluminum chlorohydrate , steareth-2, dicaprylyl ether , ceteareth-20, cyclomethicone , urea, dimethicone, phenoxyethanol, disodium edta, allantoin, parfum (fragrance), triclosan, bht, methylisothiazolinone, benzyl salicylate, butylphenyl methylpropional, citronellol, eugenol, geraniol, hexyl cinnamal, hydroxyisohexyl 3- cyclohexene carboxaldehyde, linalool, limonene.',9,1),
(10,'Déodorant Bille Tradicional','Déodorant Bille Tradicional','&sect;Description&sect; Le d&eacute;odorant Roll-On Tradicional est un antitranspirant sans alcool &eacute;thylique qui n&acute;irrite pas la peau, la laissant hydrat&eacute;e et prot&eacute;g&eacute;e tout au long de la journ&eacute;e. Il ne tache pas les v&ecirc;tements gr&acirc;ce &agrave; la pr&eacute;sence d&acute;ur&eacute;e. &sect;Conseils d&#39;utilisation&sect; Appliquer sur les zones concern&eacute;es, propres et s&egrave;ches. Eviter les zones irrit&eacute;es. &sect;Composition&sect; aqua (water), aluminum chlorohydrate , steareth-2, dicaprylyl ether , ceteareth-20, cyclomethicone , urea, dimethicone, methylparaben, disodium edta, allantoin, parfum (fragrance), triclosan, propylparaben, bht, geraniol, hexyl cinnamal.',10,1),
(11,'Coffret Sport','Coffret Sport','&sect;Description&sect; Coffret. &sect;Composition&sect; aqua (water), aluminum chlorohydrate , steareth-2, dicaprylyl ether , ceteareth-20, cyclomethicone , urea, dimethicone, methylparaben, disodium edta, allantoin, parfum (fragrance), triclosan, propylparaben, bht, geraniol, hexyl cinnamal.',11,1),
(12,'Gommage poudre pour le visage','Gommage poudre pour le visage','&sect;Description&sect; Recommand&eacute; particuli&egrave;rement pour les peaux grasses. Poudre exfoliante qui stimule le renouvellement cellulaire. Avec son effet micro-peeling elle agit en douceur, d&eacute;sobstruant les pores et offrant un nettoyage profond de la peau. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer sur visage humide une &agrave; deux fois par semaine avec des mouvements circulaires. Doser la quantit&eacute; de produit en fonction de l&acute;exfoliation souhait&eacute;e. Bien rincer. Non-indiqu&eacute; pour les peaux sensibles. &sect;Composition&sect; zea mays starch, polyethylene, sodium lauroyl glutamate, talc, mannitol, aqua (water), parfum (fragrance), silica, magnesium carbonate, triclosan, BHT, LIMONENE, LINALOOL.',16,1),
(13,'Mousse Lavante Purifiante Visage','Mousse Lavante Purifiante Visage','&sect;Description&sect; Nettoie, embellit et hydrate la peau. La Mousse Nettoyante R&eacute;g&eacute;n&eacute;ratrice &eacute;limine les cellules mortes sans endommager ou dess&eacute;cher le visage. Sa formule rafra&icirc;chit, maintient l&acute;hydratation et laisse une sensation extra douce sur la peau. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer sur visage humide par effleurage. Laisser agir 30 secondes, masser d&eacute;licatement en effectuant des mouvements circulaires, et bien rincer. &sect;Composition&sect; aqua, PEG-14M, PPG-5 ceteareth-20, TEA-cocoyl glutamate, polyquaternium 39, phenoxyethanol, caprylyl glycol, Lavandula hybrida oil, glycerin, sodium PCA, sodium lactate, propylene glycol, arginine, aspartic acid, PCA, glycine, alanine, serine, valine, proline, threonine, isoleucine, histidine, phenylalanine, bacillus ferment, limonene.',17,1),
(14,'Hydratant corporel de Lactate d’Ammonium','Hydratant corporel de Lactate d’Ammonium','&sect;Description&sect; &Eacute;mulsion hautement hydratante. Formul&eacute;e avec du lactate d&#39;ammonium, de l&#39;ur&eacute;e et de l&#39;huile de p&eacute;pins de raisin, elle est sp&eacute;cialement d&eacute;velopp&eacute;e pour les peaux pr&eacute;sentant des rugosit&eacute;s car elle agit en profondeur. Absorbtion rapide. pH neutre et sans colorant. Parfum aux vertus relaxantes. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer une fine couche sur la peau, deux fois par jour, en massant d&eacute;licatement. Ce produit ne doit pas &ecirc;tre utilis&eacute; par les femmes enceintes. &sect;Composition&sect; aqua (water), ammonium lactate, cetearyl alcohol, Vitis vinifera seed oil, glyceryl stearate SE, dimethicone, paraffinum liquidum, urea, triethanolamine, ceteareth-20, Lavandula hybrida oil, sorbitan caprylate, propanediol, benzoic acid, BHT, GERANIOL, LIMONENE, LINALOOL.',18,1),
(15,'Savon antiacné','Savon antiacné','&sect;Description&sect; Savon &agrave; base v&eacute;g&eacute;tale, enrichi en acide Salicylique (2%) et souffre (10%), indiqu&eacute; pour un usage quotidien pour les peaux grasses et acn&eacute;ique. Avec ses propri&eacute;t&eacute;s k&eacute;ratolytiques et s&eacute;bor&eacute;gulatrices, il nettoie en profondeur et contr&ocirc;le la production de sebum. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Faire mousser entre les mains avant de frotter d&eacute;licatement en effectuant des mouvements circulaires, sur votre peau humidifi&eacute;e. Rincer abondamment &agrave; l&#39;eau. Usage quotidien. Pour une meilleure efficacit&eacute; antiacn&eacute;, compl&eacute;ter le rituel en appliquant le Fluide hydratant Matifiant Visage. &sect;Composition&sect; Enxofre / sulfur (10%), &Aacute;cido Salic&iacute;lico / salicylic acid (2%), elaeis guineensis kernel oil and stearic acid, zea mays starch , calcium carbonate, talc, BHT, disodium distyrylbiphenyl disulfonate and CI 74160, etidronic acid. Teor de vol&aacute;teis: 18,94%',19,1),
(16,'Savon liquide Antiacné à base de Soufre','Savon liquide Antiacné à base de Soufre','&sect;Description&sect; Le savon liquide &agrave; base de soufre est indiqu&eacute; pour un usage quotidien et pour tout type de peau. Avec ses propri&eacute;t&eacute;s antiacn&eacute;, il nettoie en profondeur et agit comme pr&eacute;ventif. Pratique &agrave; transporter et &agrave; appliquer. Formule sans huile, au parfum d&acute;Eucalyptus. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer matin et soir sur visage humide et masser d&eacute;licatement jusqu&acute;&agrave; formation d&acute;une mousse abondante. Bien rincer. &sect;Composition&sect; Aqua (water), sodium laureth sulfate, cocamide DEA , decyl glucoside, cocamidopropyl betaine, glycerin, parfum (fragrance), polysorbate 80, citric acid, PEG-150 distearate, TEA cocoyl glutamate, triclosan, sodium chloride, buteth-3, sulfur, sodium benzotriazolyl butylphenol sulfonate, alcohol, tris tetramethylhydroxypiperidinol citrate, methylchloroisothiazolinone, methylisothiazolinone, tributyl citrate, DMDM hydantoin, CITRONELLOL, COUMARIN, GERANIOL, LIMONENE.',20,1),
(17,'Crème corporelle Urée & Huile pépins raisins','Crème corporelle Urée & Huile pépins raisins','&sect;Description&sect; Au coeur de la formule de la Cr&egrave;me Corporelle Granaderma, l&acute;action synergique de l&#39;ur&eacute;e et de l&#39;huile de p&eacute;pins de raisin permet de nourrir, hydrater en profondeur et am&eacute;liorer l&acute;&eacute;lasticit&eacute; de la peau. Elle emp&ecirc;che l&#39;apparition de vergetures et est rapidement absorb&eacute;e. Sans colorant. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer matin et soir, en massant par mouvements circulaires jusqu&acute;&agrave; absorption complete. &sect;Composition&sect; Cetearyl alcohol and sodium lauryl sulfate, paraffinum liquidum, BHT, sorbitol, urea, Vitis vinifera seed oil, butyl, ethyl, methyl, propylparaben and phenoxyethanol, parfum,aqua, CITRONELLOL, GERANIOL, HYDROXYCITRONELLAL, LINALOOL, LIMONENE, BUTYLPHENYL METHYLPROPIONAL, ALPHA ISOMETHYL IONONE.',21,1),
(18,'Gel Hydratant Matifiant Visage','Gel Hydratant Matifiant Visage','&sect;Description&sect; Le Gel Hydratant Matifiant est sp&eacute;cifiquement adapt&eacute; pour les peaux grasses et/ou en accompagnements des soins anti-acn&eacute;. Sa formule enrichie en Zinc matifie la peau instantan&eacute;ment et r&eacute;duit la taille des pores. Texture l&eacute;g&egrave;re et non grasse qui p&eacute;n&egrave;tre rapidement la peau. Sensation s&egrave;che et finition matifiante. Formule sans fragrance, sans colorant et sans parab&egrave;ne. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer matin et soir sur peau propre et s&egrave;che. &sect;Composition&sect; AQUA (WATER), DIMETHICONE, GLYCERIN, HYDROXYETHYL UREA, BUTYLENE GLYCOL, ALUMINUM STARCH OCTENYLSUCCINATE, SODIUM POLYACRYLATE, DIMETHICONE CROSSPOLYMER, FOMES OFFICINALIS EXTRACT, SORBITAN CAPRYLATE, CYCLOPENTASILOXANE, TRIDECETH-6, PEG/ PPG &ndash; 18/18 DIMETHICONE, PROPANEDIOL, AMINOMETHYL PROPANOL, BENZOIC ACID, ARCTIUM MAJUS ROOT EXTRACT, PHENOXYETHANOL, ZINC SULFATE, PEG-40 HYDROGENATED CASTOR OIL, BIOTIN.',22,1),
(19,'Fluide Hydratant Visage','Fluide Hydratant Visage','&sect;Description&sect; Le Fluide Hydratant Visage est indiqu&eacute; pour tout type de peau, m&ecirc;me les plus sensibles. Enrichi en Vitamine E, il a une action antioxydante. La pr&eacute;sence d&acute;Angico Branco lui offre une l&eacute;g&egrave;re action matifiante et le beurre de Murumuru promet une hydratatation prolong&eacute;e. Test&eacute; cliniquement. Non com&eacute;dog&egrave;ne. &sect;Conseils d&#39;utilisation&sect; Appliquer matin et soir sur peau propre et s&egrave;che. &sect;Composition&sect; AQUA (WATER), CYCLOPENTASILOXANE, ISONONYL ISONONANOATE, GLYCERIN, CETEARYL ALCOHOL, DIMETHICONE, ASTROCARYUM MURUMURU SEED BUTTER, CAPRYLIC/CAPRIC TRIGLYCERIDE, POLYSORBATE 60, TOCOPHERYL ACETATE, POLYACRYLAMIDE, SORBITAN CAPRYLATE, C13&ndash;14 ISOPARAFFIN, DIMETHICONE CROSSPOLYMER, BUTYLENE GLYCOL, PALM ALCOHOL, PROPANEDIOL, BENZOIC ACID, LAURETH 7, PIPTADENIA COLUBRINA PEEL EXTRACT, AMINOMETHYL PROPANOL, DISODIUM EDTA, THEOBROMA GRANDIFLORUM SEED BUTTER, LECITHIN, BHT, PHYTOSTERYL CANOLATE, PHENOXYETHANOL, CAPRYLYL GLYCOL, POTASSIUM SORBATE, TOCOPHEROL.',23,1),
(20,'Traditional antiseptic talc','Traditional antiseptic talc','§Description§Traditional antiseptic talc uses a formula first created in 1903, providing an array of antiseptic, antibacterial, fungicidal, healing and deodorant properties.\nIt effectively combats odours from underarms and feet and soothes the effects of chafing and prickly heat. Also prevents rashes and chilblains. Clinically tested. Economical packaging. Does not contain aluminium chlorhydroxide, reducing the risk of allergic reactions. \nFragrance : Fresh & Citric§Tips for Use§Apply to clean, dry skin.§Composition§talc, starch, sulfur, zinc oxide, boric acid, alicylic acid.',1,2);
